name: Label

on:
  workflow_call:

jobs:
  # the labels are attached as specified in `.github/labeler.yml`
  label:
    name: Attach labels
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Launch labeler
        uses: srvaroa/labeler@075ed09ed89dbe3214feeb50731ff61f9ef75cf7 # master at the time of pinning
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
