name: Scala Steward

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: "11"
      java-opts:
        required: false
        type: string
        default: ""
    secrets:
      # this needs to be a personal access token for a service account, as using the default GITHUB_TOKEN
      # doesn't trigger actions, when a PR is created (this is a known limitation of GitHub Actions, and
      # using a PAT is a documented work-around)
      github-token:
        required: true

jobs:
  scala-steward:
    runs-on: ubuntu-24.04
    env:
      JAVA_OPTS: ${{ inputs.java-opts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
          cache: 'sbt'
      - uses: sbt/setup-sbt@6bec67c98f542b9e17369bfca0ec822ac1363194 # v1, specifically v1.1.19
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@5bbb0a3f32b42774f8ba1ed18c29db5d915d2200 # v2, specifically v2.80.0
        with:
          author-name: scala-steward
          author-email: scala-steward
          repo-config: .scala-steward.conf
          ignore-opts-files: false
          github-token: ${{ secrets.github-token }}
