name: Label

on:
  workflow_call:

jobs:
  report:
    runs-on: ubuntu-24.04
    # If the workflow run was skipped or cancelled this action would fail, generating a test report is unnecessary.
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: dorny/test-reporter@3d76b34a4535afbd0600d347b09a6ee5deb3ed7f # v2, specifically v2.6.0
        with:
          artifact: '/tests-results(.*)/'
          name: 'Test report for $1'
          path: '**/test-reports/TEST*.xml'
          reporter: java-junit
          list-tests: 'failed'
