name: Label

on:
  workflow_call:

jobs:
  report:
    runs-on: ubuntu-24.04
    # If the workflow run was skipped or cancelled this action would fail, generating a test report is unnecessary.
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: dorny/test-reporter@d1b5dff021aa968b288b02285a8bf47471c5928a # v2, specifically v3.2.0
        with:
          artifact: '/tests-results(.*)/'
          name: 'Test report for $1'
          path: '**/test-reports/TEST*.xml'
          reporter: java-junit
          list-tests: 'failed'
